"""empty message

Revision ID: aa7c1ee9c680
Revises: 
Create Date: 2025-03-15 09:22:25.232158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa7c1ee9c680'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('music',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('lyrics', sa.String(length=3000), nullable=True),
    sa.Column('prompt', sa.String(length=2048), nullable=False),
    sa.Column('negative_prompt', sa.String(length=2048), nullable=True),
    sa.Column('input_file', sa.String(length=2048), nullable=True),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('steps', sa.Integer(), nullable=False),
    sa.Column('cfg_strength', sa.Float(), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('dt_created', sa.DateTime(), nullable=False),
    sa.Column('is_favorite', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('inference_server', sa.String(length=256), nullable=False),
    sa.Column('lrc_prompt', sa.String(length=2048), nullable=False),
    sa.Column('lrc_model', sa.String(length=256), nullable=False),
    sa.Column('processing_status', sa.Enum('NEW', 'IN_PROGRESS', 'COMPLETE', name='musicprocessingenum'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prompt',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('prompt', sa.String(length=2048), nullable=False),
    sa.Column('category', sa.Enum('LRC', 'POET', name='promptycategoryenum'), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('dt_created', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prompt')
    op.drop_table('music')
    # ### end Alembic commands ###
